In [1]:
# Import Dependencies
from pymongo import MongoClient
from config import cloudM, cloudMpassword
import pandas as pd
import numpy as np
import datetime as dt
import csv
import re

In [2]:
#create a variable for columns to keep
#did not include the note columns because it would drop some data due to null
columns = ["Country", "Geography: Geographic coordinates", "Geography: Map references", "Geography: Area - total",
            "Economy: Real GDP (purchasing power parity)", 
            "Economy: Real GDP growth rate",
            "Economy: Real GDP per capita",
            "Economy: Current account balance",
            "Economy: Exports",
            "Economy: Exports - partners",
            "Economy: Reserves of foreign exchange and gold",
            "Energy: Electricity access - electrification - total population",
            "Economy: Credit ratings - Moody's rating",
            "Economy: Credit ratings - Standard & Poors rating",
            "Economy: Credit ratings - Fitch rating",
            "Economy: Unemployment rate",
            "Economy: Population below poverty line",
            "Economy: Household income or consumption by percentage share - highest 10%",
            "People and Society: Population",
            "People and Society: Nationality - noun",
            "People and Society: Nationality - adjective",
            "People and Society: Languages",
            "People and Society: Religions",
            "People and Society: Age structure - 0-14 years",
            "People and Society: Age structure - 15-24 years",
            "People and Society: Age structure - 25-54 years",
            "People and Society: Age structure - 55-64 years",
            "People and Society: Median age - total",
            "People and Society: Median age - male",
            "People and Society: Median age - female",
            "People and Society: Population growth rate",
            "People and Society: Birth rate",
            "People and Society: Death rate",
            "People and Society: Net migration rate",
            "People and Society: Urbanization - urban population",
            "People and Society: Sex ratio - at birth",
            "People and Society: Sex ratio - 65 years and over",
            "People and Society: Sex ratio - total population",
            "People and Society: Infant mortality rate - total",
            "People and Society: Life expectancy at birth - total population",
            "People and Society: Life expectancy at birth - male",
            "People and Society: Life expectancy at birth - female",
            "People and Society: Total fertility rate",
            "People and Society: Obesity - adult prevalence rate",
            "People and Society: Tobacco use - total",
            "Communications: Internet users - total",
            "Communications: Internet users - percent of population",
            "Military and Security: Military expenditures",
            "Military and Security: Military service age and obligation",
            "Terrorism: Terrorist group(s)", "Military and Security: Military - note"]

In [3]:
#load data and create df to clean
data = pd.read_csv("countries.csv")
#previouly determined all fields were objects, load as string for cleaning
df = pd.DataFrame(data).astype("string")
df = df.loc[:, columns].copy()
#df.head(2)

In [4]:
#drop null values & determing number of rows
df = df.dropna()
len(df)

48

In [5]:
#set index to country
df.set_index('Country')
#df.head(2)

,Geography: Geographic coordinates,Geography: Map references,Geography: Area - total,Economy: Real GDP (purchasing power parity),Economy: Real GDP growth rate,Economy: Real GDP per capita,Economy: Current account balance,Economy: Exports,Economy: Exports - partners,Economy: Reserves of foreign exchange and gold,...,People and Society: Life expectancy at birth - female,People and Society: Total fertility rate,People and Society: Obesity - adult prevalence rate,People and Society: Tobacco use - total,Communications: Internet users - total,Communications: Internet users - percent of population,Military and Security: Military expenditures,Military and Security: Military service age and obligation,Terrorism: Terrorist group(s),Military and Security: Military - note
Country,,,,,,,,,,,,,,,,,,,,,
Argentina,"34 00 S, 64 00 W",South America,"2,780,400 sq km",$893.31 billion (2020 est.)$991.52 billion (20...,-2.03% (2019 est.)-2.53% (2018 est.)2.83% (201...,"$19,700 (2020 est.)$22,100 (2019 est.)$22,800 ...",-$3.997 billion (2019 est.)-$27.049 billion (2...,$64.18 billion (2020 est.) note: data are in c...,"Brazil 16%, China 11%, United States 7%, Chile...",$55.33 billion (31 December 2017 est.)$38.43 b...,...,81.59 years (2022 est.),2.18 children born/woman (2022 est.),28.3% (2016),24.5% (2020 est.),"39,024,016 (2020 est.)",86% (2020 est.),0.8% of GDP (2021 est.)0.8% of GDP (2020)0.7% ...,18-24 years of age for voluntary military serv...,Hizballah,Argentina has Major Non-NATO Ally (MNNA) statu...
Austria,"47 20 N, 13 20 E",Europe,"83,871 sq km",$463.12 billion (2020 est.)$495.8 billion (201...,1.42% (2019 est.)2.58% (2018 est.)2.4% (2017 e...,"$51,900 (2020 est.)$55,800 (2019 est.)$55,300 ...",$12.667 billion (2019 est.)$5.989 billion (201...,$226.79 billion (2020 est.) note: data are in ...,"Germany 28%, United States 7%, Italy 6%, Switz...",$21.57 billion (31 December 2017 est.)$23.36 b...,...,85.04 years (2022 est.),1.51 children born/woman (2022 est.),20.1% (2016),26.4% (2020 est.),"7,846,840 (2020 est.)",88% (2020 est.),0.9% of GDP (2021 est.)0.7% of GDP (2020 est.)...,"registration requirement at age 17, the legal ...",Islamic State of Iraq and ash-Sham (ISIS),"Austria is constitutionally non-aligned, but i..."
Azerbaijan,"40 30 N, 47 30 E",Asia,"86,600 sq km",$138.51 billion (2020 est.)$144.74 billion (20...,0.1% (2017 est.)-3.1% (2016 est.)0.6% (2015 est.),"$13,700 (2020 est.)$14,400 (2019 est.)$14,200 ...",$1.685 billion (2017 est.)-$1.363 billion (201...,$15.21 billion (2020 est.) note: data are in c...,"Italy 28%, Turkey 15%, Israel 7%, Germany 5%, ...",$6.681 billion (31 December 2017 est.)$7.142 b...,...,77.41 years (2022 est.),1.86 children born/woman (2022 est.),19.9% (2016),24% (2020 est.),"8,579,153 (2020 est.)",85% (2020 est.),5.2% of GDP (2021 est.)5.4% of GDP (2020 est.)...,men age 18-35 years for compulsory military se...,Islamic State of Iraq and ash-Sham (ISIS); Isl...,"since November 2020, Russia has deployed about..."
Bangladesh,"24 00 N, 90 00 E",Asia,"148,460 sq km",$793.49 billion (2020 est.)$775.08 billion (20...,7.4% (2017 est.)7.2% (2016 est.)6.8% (2015 est.),"$4,800 (2020 est.)$4,800 (2019 est.)$4,400 (20...",-$5.322 billion (2017 est.)$1.391 billion (201...,$38.78 billion (2020 est.) note: data are in c...,"United States 15%, Germany 14%, United Kingdom...",$33.42 billion (31 December 2017 est.)$32.28 b...,...,76.96 years (2022 est.),2.09 children born/woman (2022 est.),3.6% (2016),34.7% (2020 est.),"41,172,346 (2020 est.)",25% (2020 est.),1.2% of GDP (2021 est.)1.3% of GDP (2020 est.)...,16-21 years of age for voluntary military serv...,Harakat ul-Jihad-i-Islami/Bangladesh; Islamic ...,the military’s chief areas of focus are border...
Belgium,"50 50 N, 4 00 E",Europe,"30,528 sq km",$557.11 billion (2020 est.)$594.47 billion (20...,1.41% (2019 est.)1.49% (2018 est.)1.9% (2017 e...,"$48,200 (2020 est.)$51,700 (2019 est.)$51,100 ...",$1.843 billion (2019 est.)-$4.135 billion (201...,$414.79 billion (2020 est.) note: data are in ...,"Germany 17%, France 14%, Netherlands 13%, Unit...",$26.16 billion (31 December 2017 est.)$24.1 bi...,...,84.59 years (2022 est.),1.77 children born/woman (2022 est.),22.1% (2016),23.4% (2020 est.),"10,620,701 (2020 est.)",92% (2020 est.),1.1% of GDP (2021 est.)1% of GDP (2020)0.9% of...,18 years of age for male and female voluntary ...,Islamic Revolutionary Guard Corps/Qods Force; ...,Belgium is a member of NATO and was one of the...
Benin,"9 30 N, 2 15 E",Africa,"112,622 sq km",$40.29 billion (2020 est.)$38.79 billion (2019...,5.6% (2017 est.)4% (2016 est.)2.1% (2015 est.),"$3,300 (2020 est.)$3,300 (2019 est.)$3,200 (20...",-$1.024 billion (2017 est.)-$808 million (2016...,$3.58 billion (2019 est.) note: data are in cu...,"Nigeria 25%, Bangladesh 14%, United Arab Emira...",$698.9 million (31 December 2017 est.)$57.5 mi...,...,64.14 years (2022 est.),5.43 children born/woman (2022 est.),9.6% (2016),6.9% (2020 est.),"3,152,032 (2020 est.)",26% (2020 est.),0.7% of GDP (2021 est.)0.5% of GDP (2020 est.)...,18-35 years of age for selective compulsory an...,al-Qa’ida (Jama’at Nusrat al Islam wal Muslime...,"as of 2022, a key focus for the security force..."
Brazil,"10 00 S, 55 00 W",South America,"8,515,770 sq km","$2,989,430,000,000 (2020 est.)$3,115,910,000,0...",1.13% (2019 est.)1.2% (2018 est.)1.62% (2017 e...,"$14,100 (2020 est.)$14,800 (2019 est.)$14,700 ...",-$50.927 billion (2019 est.)-$41.54 billion (2...,$239.18 billion (2020 est.) note: data are in ...,"China 28%, United States 13% (2019)",$374 billion (31 December 2017 est.)$367.5 bil...,...,79.5 years (2022 est.),1.8 children born/woman (2022 est.),22.1% (2016),12.8% (2020 est.),"172,173,121 (2020 est.)",81% (2020 est.),1.3% of GDP (2021 est.)1.4% of GDP (2020)1.4% ...,18-45 years of age for compulsory military ser...,Hizballah (2022),the origins of Brazil's military stretch back ...
Bulgaria,"43 00 N, 25 00 E",Europe,"110,879 sq km",$155.06 billion (2020 est.)$161.78 billion (20...,3.39% (2019 est.)3.2% (2018 est.)3.5% (2017 est.),"$22,400 (2020 est.)$23,200 (2019 est.)$22,200 ...",$2.06 billion (2019 est.)$611 million (2018 est.),$39.27 billion (2020 est.) note: data are in c...,"Germany 16%, Romania 8%, Italy 7%, Turkey 7%, ...",$28.38 billion (31 December 2017 est.)$25.13 b...,...,78.97 years (2022 est.),1.5 children born/woman (2022 est.),25% (2016),39% (2020 est.),"4,853,811 (2020 est.)",70% (2020 est.),1.6% of GDP (2021 est.)1.6% of GDP (2020)3.1% ...,18-27 years of age for voluntary military serv...,Islamic State of Iraq and ash-Sham (ISIS); Isl...,Bulgaria officially became a member of NATO in...
Cameroon,"6 00 N, 12 00 E",Africa,"475,440 sq km",$94.94 billion (2020 est.)$94.25 billion (2019...,3.5% (2017 est.)4.6% (2016 est.)5.7% (2015 est.),"$3,600 (2020 est.)$3,600 (2019 est.)$3,600 (20...",-$932 million (2017 est.)-$1.034 billion (2016...,$7.73 billion (2019 est.) note: data are in cu...,"China 17%, Netherlands 14%, Italy 9%, United A...",$3.235 billion (31 December 2017 est.)$2.26 bi...,...,65.09 years (2022 est.),4.55 children born/woman (2022 est.),11.4% (2016),7.3% (2020 est.),"10,087,428 (2020 est.)",38% (2020 est.),1% of GDP (2021 est.)1% of GDP (2020 est.)1.4%...,18-23 years of age for male and female volunta...,Boko Haram; Islamic State of Iraq and ash-Sham...,"as of 2022, the FAC was largely focused on the..."
Canada,"60 00 N, 95 00 W",North America,"9,984,670 sq km","$1,742,790,000,000 (2020 est.)$1,842,330,000,0...",1.66% (2019 est.)2.02% (2018 est.)3.17% (2017 ...,"$45,900 (2020 est.)$49,000 (2019 est.)$48,800 ...",-$35.425 billion (2019 est.)-$42.862 billion (...,$477.31 billion (2020 est.) note: data are in ...,US 73% (2019),$86.68 billion (31 December 2017 est.)$82.72 b...,...,86.21 years (2022 est.),1.57 children born/woman (2022 est.),29.4% (2016),13% (2020 est.),"36,896,088 (2020 est.)",97% (2020 est.),1.4% of GDP (2021 est.)1.4% of GDP (2020)1.3% ...,17 years of age for voluntary male and female ...,Islamic State of Iraq and ash-Sham (ISIS); Hiz...,Canada is a member of NATO and was one of the ...
Colombia,"4 00 N, 72 00 W",South America,"1,138,910 sq km",$683.94 billion (2020 est.)$734.22 billion (20...,3.26% (2019 est.)2.51% (2018 est.)1.36% (2017 ...,"$13,400 (2020 est.)$14,600 (2019 est.)$14,300 ...",-$13.748 billion (2019 est.)-$13.118 billion (...,$39.14 billion (2020 est.) note: data are in c...,"United States 31%, China 11%, Panama 6%, Ecuad...",$47.13 billion (31 December 2017 est.)$46.18 b...,...,78.69 years (2022 est.),1.95 children born/woman (2022 est.),22.3% (2016),8.5% (2020 est.),"35,618,019 (2020 est.)",70% (2020 est.),3% of GDP (2021 est.)3% of GDP (2020 est.)3.1%...,18-24 years of age for compulsory (men) and vo...,National Liberation Army (ELN); Revolutionary ...,"as of 2022, the Colombian Armed Forces were pr..."
Cyprus,"35 00 N, 33 00 E",Middle East,"9,251 sq km (of which 3,355 sq km are in north...",$33.67 billion (2020 est.)$35.48 billion (2019...,3.08% (2019 est.)5.25% (2018 est.)5.16% (2017 ...,"$37,700 (2020 est.)$40,200 (2019 est.)$39,600 ...",-$1.578 billion (2019 est.)-$958 million (2018...,$16.1 billion (2020 est.) note: data are in cu...,"India 9%, Greece 9%, Libya 8%, United Kingdom ...",$888.2 million (31 December 2017 est.)$817.7 m...,...,82.68 years (2022 est.),1.48 children born/woman (2022 est.),21.8% (2016),35.1% (2020 est.),"1,098,699 (2020 est.)",91% (2020 est.),2% of GDP (2021 est.)1.8% of GDP (2020 est.)1....,Cypriot National Guard (CNG): 18-50 years of a...,Islamic State of Iraq and ash-Sham (ISIS),the United Nations Peacekeeping Force in Cypru...
Denmark,"56 00 N, 10 00 E",Europe,"43,094 sq km",$326.2 billion (2020 est.)$335.36 billion (201...,2.85% (2019 est.)2.18% (2018 est.)2.83% (2017 ...,"$55,900 (2020 est.)$57,700 (2019 est.)$56,300 ...",$30.935 billion (2019 est.)$24.821 billion (20...,$191.53 billion (2020 est.) note: data are in ...,"Germany 14%, United States 11%, Sweden 10%, Un...",$75.25 billion (31 December 2017 est.)$64.25 b...,...,83.71 years (2022 est.),1.77 children born/woman (2022 est.),19.7% (2016),17.5% (2020 est.),"5,656,462 (2020 est.)",97% (2020 est.),1.4% of GDP (2021 est.)1.4% of GDP (2020)1.3% ...,18 years of age for compulsory and voluntary m...,Islamic State of Iraq and ash-Sham (ISIS); Isl...,Denmark is a member of NATO and was one of the...
Egypt,"27 00 N, 30 00 E",Africa,"1,001,450 sq km","$1,223,040,000,000 (2020 est.)$1,180,890,000,0...",4.2% (2017 est.)4.3% (2016 est.)4.4% (2015 est.),"$12,000 (2020 est.)$11,800 (2019 est.)$11,400 ...",-$8.915 billion (2019 est.)-$7.682 billion (20...,$40.1 billion (2020 est.) note: data are in cu...,"United States 9%, United Arab Emirates 6%, Ita...",$35.89 billion (31 December 2017 est.)$23.2 bi...,...,75.72 years (2022 est.),2.88 children born/woman (2022 est.),32% (2016),24.3% (2020 est.),"73,680,770 (2020 est.)",72% (2020 est.),1.3% of GDP (2021 est.)1.3% of GDP (2020)1.3% ...,voluntary enlistment possible from age 16 (men...,Army of Islam; Islamic State of Iraq and ash-S...,"since 2011, the Egyptian Armed Forces, police,..."
Ethiopia,"8 00 N, 38 00 E",Africa,"1,104,300 sq km",$264.05 billion (2020 est.)$248.97 billion (20...,10.9% (2017 est.)8% (2016 est.)10.4% (2015 est.),"$2,300 (2020 est.)$2,200 (2019 est.)$2,100 (20...",-$6.551 billion (2017 est.)-$6.574 billion (20...,$7.62 billion (2018 est.) note: data are in cu...,"China 17%, United States 16%, United Arab Emir...",$3.013 billion (31 December 2017 est.)$3.022 b...,...,70.44 years (2022 est.),3.99 children born/woman (2022 est.),4.5% (2016),5.1% (2020 est.),"27,591,260 (2020 est.)",24% (2020 est.),0.5% of GDP (2021 est.)0.5% of GDP (2020 est.)...,18 years of age for voluntary military service...,al-Shabaab; IRGC/Qods Force,each of the nine states has a regional and/or ...
Germany,"51 00 N, 9 00 E",Europe,"357,022 sq km","$4,238,800,000,000 (2020 est.)$4,457,050,000,0...",0.59% (2019 est.)1.3% (2018 est.)2.91% (2017 e...,"$50,900 (2020 est.)$53,600 (2019 est.)$53,500 ...",$280.238 billion (2019 est.)$297.434 billion (...,"$1,671,650,000,000 (2020 est.) note: data are ...","United States 9%, France 8%, China 7%, Netherl...",$200.1 billion (31 December 2017 est.)$173.7 b...,...,84 years (2022 est.),1.57 children born/woman (2022 est.),22.3% (2016),22% (2020 est.),"74,844,784 (2020 est.)",90% (2020 est.),1.5% of GDP (2021 est.)1.5% of GDP (2020)1.4% ...,17-23 years of age for male and female volunta...,Islamic Revolutionary Guard Corps/Qods Force; ...,the Federal Republic of Germany joined NATO in...
Greece,"39 00 N, 22 00 E",Europe,"131,957 sq km",$292.4 billion (2020 est.)$318.68 billion (201...,1.87% (2019 est.)1.91% (2018 est.)1.44% (2017 ...,"$27,300 (2020 est.)$29,700 (2019 est.)$29,200 ...",-$3.114 billion (2019 est.)-$6.245 billion (20...,$59.02 billion (2020 est.) note: data are in c...,"Italy 10%, Germany 7%, Turkey 5%, Cyprus 5%, B...",$7.807 billion (31 December 2017 est.)$6.026 b...,...,84.2 years (2022 est.),1.4 children born/woman (2022 est.),24.9% (2016),33.5% (2020 est.),"8,346,434 (2020 est.)",78% (2020 est.),3.6% of GDP (2021 est.)2.9% of GDP (2020)2.3% ...,19-45 years of age for compulsory military ser...,Islamic State of Iraq and ash-Sham (ISIS); Rev...,Greece joined NATO in 1952
India,"20 00 N, 77 00 E",Asia,"3,287,263 sq km","$8,443,360,000,000 (2020 est.)$9,174,040,000,0...",4.86% (2019 est.)6.78% (2018 est.)6.55% (2017 ...,"$6,100 (2020 est.)$6,700 (2019 est.)$6,500 (20...",-$29.748 billion (2019 est.)-$65.939 billion (...,$484.95 billion (2020 est.) note: data are in ...,"United States 17%, United Arab Emirates 9%, Ch...",$409.8 billion (31 December 2017 est.)$359.7 b...,...,69.16 years (2022 est.),2.1 children born/woman (2022 est.),3.9% (2016),27.2% (2020 est.),593.4 million (2020 est.),43% (2020 est.),2.2% of GDP (2021 est.)2.6% of GDP (2020 est.)...,16-18 years of age for voluntary military serv...,Harakat,"as of 2022, the Indian Armed Forces were chief..."
Indonesia,"5 00 S, 120 00 E",Southeast Asia,"1,904,569 sq km","$3,130,470,000,000 (2020 est.)$3,196,620,000,0...",5.03% (2019 est.)5.17% (2018 est.)5.07% (2017 ...,"$11,400 (2020 est.)$11,800 (2019 est.)$11,400 ...",-$30.359 billion (2019 est.)-$30.633 billion (...,$178.26 billion (2020 est.) note: data are in ...,"China 15%, United States 10%, Japan 9%, Singap...",$130.2 billion (31 December 2017 est.),...,75.4 years (2022 est.),2.01 children born/woman (2022 est.),6.9% (2016),37.6% (2020 est.),"147,702,755 (2020 est.)",54% (2020 est.),0.8% of GDP (2021 est.)0.8% of GDP (2020)0.8% ...,18-45 years of age for voluntary military serv...,Islamic State of Iraq and ash-Sham (aka Jemaah...,"as of 2022, Indonesian military and police for..."
Iraq,"33 00 N, 44 00 E",Middle East,"438,317 sq km",$372.27 billion (2020 est.)$415.32 billion (20...,-2.1% (2017 est.)13.1% (2016 est.)2.5% (2015 e...,"$9,300 (2020 est.)$10,600 (2019 est.)$10,300 (...",$4.344 billion (2017 est.)-$13.38 billion (201...,$50.61 billion (2020 est.) note: data are in c...,"China 26%, India 24%, South Korea 9%, United S...",$48.88 billion (31 December 2017 est.)$45.36 b...,...,75.15 years (2022 est.),3.25 children born/woman (2022 est.),30.4% (2016),18.5% (2020 est.),"24,133,502 (2020 est.)",60% (2020 est.),3.7% of GDP (2021 est.)4.1% of GDP (2020 est.)...,18-40 years of age for voluntary military serv...,Ansar al-Islam; Asa'ib Ahl al-Haq; Islamic Rev...,"- as of 2022, Iraqi security forces (ISF) cont..."
Ireland,"53 00 N, 8 00 W",Europe,"70,273 sq km",$447.97 billion (2020 est.)$433.17 billion (20...,5.86% (2019 est.)9.42% (2018 est.)9.49% (2017 ...,"$89,700 (2020 est.)$87,800 (2019 est.)$84,300 ...",-$44.954 billion (2019 est.)$24.154 billion (2...,$502.31 billion (2019 est.) note: data are in ...,"United States 28%, Belgium 10%, Germany 10%, U...",$4.412 billion (31 December 2017 est.)$2.203 b...,...,84.1 years (2022 est.),1.92 children born/woman (2022 est.),25.3% (2016),20.8% (2020 est.),"4,586,820 (2020 est.)",92% (2020 est.),0.3% of GDP (2021)0.3% of GDP (2020)0.3% of GD...,18-25 years of age for male and female volunta...,Continuity Irish Republican Army; New Irish Re...,the Irish Defense Forces trace their origins b...
Israel,"31 30 N, 34 45 E",Middle East,"21,937 sq km",$353.39 billion (2020 est.)$362.23 billion (20...,-2.6% (2020 est.)3.28% (2019 est.)3.69% (2018 ...,"$38,300 (2020 est.)$40,000 (2019 est.)$39,400 ...",$20.642 billion (2020 est.)$13.411 billion (20...,$113.87 billion (2020 est.) note: data are in ...,"United States 26%, China 9%, United Kingdom 7%...",$173.292 billion (2020 est.)$113 billion (31 D...,...,85.34 years (2022 est.),2.56 children born/woman (2022 est.),26.1% (2016),21.2% (2020 est.),"8,293,590 (2020 est.)",90% (2020 est.),5% of GDP (2021 est.)5% of GDP (2020 est.)5.2%...,18 years of age for compulsory military servic...,Islamic State of Iraq and ash-Sham (ISIS); Pop...,the United Nations Disengagement Observer Forc...
Italy,"42 50 N, 12 50 E",Europe,"301,340 sq km","$2,322,140,000,000 (2020 est.)$2,548,190,000,0...",0.34% (2019 est.)0.83% (2018 est.)1.73% (2017 ...,"$39,000 (2020 est.)$42,700 (2019 est.)$42,100 ...",$59.517 billion (2019 est.)$51.735 billion (20...,$558.26 billion (2020 est.) note: data are in ...,"Germany 12%, France 11%, United States 10%, Un...",$151.2 billion (31 December 2017 est.)$130.6 b...,...,85.08 years (2022 est.),1.22 children born/woman (2022 est.),19.9% (2016),23.1% (2020 est.),"41,614,669 (2020 est.)",70% (2020 est.),1.5% of GDP (2021 est.)1.6% of GDP (2020)1.2% ...,18-25 years of age for voluntary military serv...,Islamic State of Iraq and ash-Sham (ISIS),Italy is a member of NATO and was one of the o...
Jordan,"31 00 N, 36 00 E",Middle East,"89,342 sq km",$100.16 billion (2020 est.)$101.74 billion (20...,2% (2019 est.)1.94% (2018 est.)2.12% (2017 est.),"$9,800 (2020 est.)$10,100 (2019 est.)$10,000 (...",-$1.222 billion (2019 est.)-$2.964 billion (20...,$16.29 billion (2019 est.) note: data are in c...,"United States 21%, Saudi Arabia 13%, India 8%,...",$15.56 billion (31 December 2017 est.)$15.54 b...,...,77.6 years (2022 est.),2.96 children born/woman (2022 est.),35.5% (2016),34.8% (2020 est.),"6,768,137 (2019 est.)",67% (2019 est.),5% of GDP (2021 est.)5% of GDP (2020 est.)5.6%...,17 years of age for voluntary male military se...,Islamic State of Iraq and ash-Sham (ISIS),the Jordanian military traces its origins back...
Malaysia,"2 30 N, 112 30 E",Southeast Asia,"329,847 sq km",$855.6 billion (2020 est.)$906.24 billion (201...,4.31% (2019 est.)4.77% (2018 est.)5.81% (2017 ...,"$26,400 (2020 est.)$28,400 (2019 est.)$27,600 ...",$12.295 billion (2019 est.)$8.027 billion (201...,$207.37 billion (2020 est.) note: data are in ...,"Singapore 13%, China 13%, United States 11%, H...",$102.4 billion (31 December 2017 est.)$94.5 bi...,...,77.87 years (2022 est.),1.75 children born/woman (2022 est.),15.6% (2016),22.5% (2020 est.),"29,129,398 (2020 est.)",90% (2020 est.),1% of GDP (2021 est.)1.1% of GDP (2020)1% of G...,17 years 6 months of age for voluntary militar...,Islamic State of Iraq and ash-Sham (ISIS); Jem...,maritime security has long been a top priority...
Morocco,"28 30 N, 10 00 W",Africa,"716,550 sq km",$259.42 billion (2020 est.)$279.3 billion (201...,2.5% (2019 est.)2.96% (2018 est.)3.98% (2017 e...,"$6,900 (2020 est.)$7,500 (2019 est.)$7,400 (20...",-$5.075 billion (2019 est.)-$6.758 billion (20...,$37.52 billion (2020 est.) note: data are in c...,"Spain 23%, France 19% (2019)",$26.27 billion (31 December 2017 est.)$25.37 b...,...,75.46 years (2022 est.),2.29 children born/woman (2022 est.),26.1% (2016),14.5% (2020 est.),"31,004,869 (2020 est.)",84% (2020 est.),4.5% of GDP (2021 est.)4.5% of GDP (2020 est.)...,19-25 years of age for 12-month compulsory mil...,Islamic State of Iraq and ash-Sham (ISIS),Moroccan military forces were engaged in comba...

In [6]:
df_a = df.rename(columns = 
                {"Geography: Geographic coordinates" : "Geographic coordinates", "Geography: Map references" : "Map references",      
                "Economy: Real GDP (purchasing power parity)" : "Real GDP", "Economy: Real GDP growth rate" : "GDP Growth Rate", 
                "Economy: Real GDP per capita" : "GDP per Capita",
                "Economy: Current account balance": "Econ Current Acct Bal",
                "Economy: Exports" : "Exports",
                "Economy: Exports - partners" : "Exports - Partners",
                "Economy: Reserves of foreign exchange and gold" : "Foreign Exchange & Gold",
                "Energy: Electricity access - electrification - total population" :"Tota; Population Electrication",
                "Economy: Credit ratings - Moody's rating" : "Moody's Rating",
                "Economy: Credit ratings - Standard & Poors rating" : "Standard & Poors Rating",
                "Economy: Credit ratings - Fitch rating" : "Fitch Rating",
                "Economy: Unemployment rate" : "Unemployment Rate",
                "Economy: Population below poverty line" : "Population below poverty line",
                "Economy: Household income or consumption by percentage share - highest 10%" : "Household income or consumption by % -highest 10%",
                "People and Society: Population" : "Population",
                "People and Society: Nationality - noun" : "Nationality - noun",
                "People and Society: Nationality - adjective" : "Nationality - adjective",
                 "People and Society: Languages" : "Languages",
                "People and Society: Religions" : "Religions",
                "People and Society: Age structure - 0-14 years" : "Age structure - 0-14 years",
                "People and Society: Age structure - 15-24 years" : "Age structure - 15-24 years",
                "People and Society: Age structure - 25-54 years" : "Age structure - 25-54 years",
                "People and Society: Age structure - 55-64 years" : "Age structure - 55-64 years",
                "People and Society: Median age - total" : "Total Median age",
                "People and Society: Median age - male" : "Male Median age",
                "People and Society: Median age - female" : "Female Median age",
                "People and Society: Population growth rate" : "Population growth rate",
                "People and Society: Birth rate" : "Birth rate",
                "People and Society: Death rate" : "Death rate",
                "People and Society: Net migration rate" : "Net migration rate",
                "People and Society: Urbanization - urban population" : "Urban Population",
                "People and Society: Sex ratio - at birth" : "Sex ratio at Birth",
                "People and Society: Sex ratio - 65 years and over" : "65 & Older Sex Ratio",
                "People and Society: Sex ratio - total population" : "Total Pop Sex Ratio",
                "People and Society: Infant mortality rate - total" : "Total Infant Mortality Rate",
                "People and Society: Life expectancy at birth - total population" : "Total Pop Life expectancy at birth",
                "People and Society: Life expectancy at birth - male" : "Male Life expectancy at birth",
                "People and Society: Life expectancy at birth - female" : "Female Life expectancy at birth",
                "People and Society: Total fertility rate" : "Total fertility rate",
                "People and Society: Obesity - adult prevalence rate" : "Adult Obesity Prev Rate",
                "People and Society: Tobacco use - total" : "Total Tobacco use",
                "Communications: Internet users - total" : "Total Internet Users",
                "Communications: Internet users - percent of population" : "Internet users - % of Pop",
                "Military and Security: Military expenditures" : "Military expenditures",
                "Military and Security: Military service age and obligation" : "Military service age and obligation"})

In [7]:
df_a.columns.tolist()

['Country',
 'Geographic coordinates',
 'Map references',
 'Geography: Area - total',
 'Real GDP',
 'GDP Growth Rate',
 'GDP per Capita',
 'Econ Current Acct Bal',
 'Exports',
 'Exports - Partners',
 'Foreign Exchange & Gold',
 'Tota; Population Electrication',
 "Moody's Rating",
 'Standard & Poors Rating',
 'Fitch Rating',
 'Unemployment Rate',
 'Population below poverty line',
 'Household income or consumption by % -highest 10%',
 'Population',
 'Nationality - noun',
 'Nationality - adjective',
 'Languages',
 'Religions',
 'Age structure - 0-14 years',
 'Age structure - 15-24 years',
 'Age structure - 25-54 years',
 'Age structure - 55-64 years',
 'Total Median age',
 'Male Median age',
 'Female Median age',
 'Population growth rate',
 'Birth rate',
 'Death rate',
 'Net migration rate',
 'Urban Population',
 'Sex ratio at Birth',
 '65 & Older Sex Ratio',
 'Total Pop Sex Ratio',
 'Total Infant Mortality Rate',
 'Total Pop Life expectancy at birth',
 'Male Life expectancy at birth',
 'Female Life expectancy at birth',
 'Total fertility rate',
 'Adult Obesity Prev Rate',
 'Total Tobacco use',
 'Total Internet Users',
 'Internet users - % of Pop',
 'Military expenditures',
 'Military service age and obligation',
 'Terrorism: Terrorist group(s)',
 'Military and Security: Military - note']

In [8]:
#change geo coordinate to lat and long columns
df_a[["LATITUDE", "LONGITUDE"]] = df_a["Geographic coordinates"].str.split(",", expand = True)

In [9]:
#check columns
#df_a["LATITUDE"]
#df_a["LONGITUDE"]
#df_a.columns.tolist()

In [10]:
# slice to make 2019 real GDP column
df_a["2020 Real GDP"] = df_a["Real GDP"].str[:15]

In [11]:
#remove $ from new column
df_a["2020 Real GDP"] = df_a["2020 Real GDP"].str.replace("$", "")

#remove billion
df_a["2020 Real GDP"] = df_a["2020 Real GDP"].str.replace("billion", "")

#remove comma
df_a["2020 Real GDP"] = df_a["2020 Real GDP"].str.replace(",", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

In [12]:
print(df_a["2020 Real GDP"])

10         893.31
15         463.12
16         138.51
20         793.49
23         557.11
25         40.29
32      2989430000
36         155.06
42         94.94
43      1742790000
52         683.94
62         33.67
64         326.2
70      1223040000
76         264.05
88      4238800000
91         292.4
108     8443360000
109     3130470000
111        372.27
112        447.97
114        353.39
115     2322140000
122        100.16
144        855.6
159        259.42
160        38.42
165        945.48
170     1013530000
177     1021130000
183        87.98
184        371.29
185        871.56
187     1223460000
188        331.64
191        556.07
192     3875690000
215        680.04
217     1714860000
219        274.8
223        524.75
224        590.71
235        114.97
236     2393960000
240        99.61
243     2797980000
244    19846720000
246        239.42
Name: 2020 Real GDP, dtype: string

In [13]:
# slice to make 2019 real GDP column
df_a["2019 Real GDP"] = df_a["Real GDP"].str[28:48]

In [14]:
#remove $ from new column
df_a["2019 Real GDP"] = df_a["2019 Real GDP"].str.replace("$", "")

#remove billion
df_a["2019 Real GDP"] = df_a["2019 Real GDP"].str.replace("billion", "")

# #remove comma
df_a["2019 Real GDP"] = df_a["2019 Real GDP"].str.replace(",", "")

# remove (2019)
df_a["2019 Real GDP"] = df_a["2019 Real GDP"].str.replace("\(2019", "")

#remove e
df_a["2019 Real GDP"] = df_a["2019 Real GDP"].str.replace("e", "")

# remove .)
df_a["2019 Real GDP"] = df_a["2019 Real GDP"].str.replace(".\)", "")

# remove t
#remove e
df_a["2019 Real GDP"] = df_a["2019 Real GDP"].str.replace("t", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:11: FutureWarning: The default value of regex will change from True to False in a future version.
  # This is added back by InteractiveShellApp.init_path()
/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:17: FutureWarning: The default value of regex will change from True to False in a future version.

In [15]:
df_a["2019 Real GDP"]

10          991.52
15          495.8
16          144.74
20          775.08
23          594.47
25           8.79
32     3115910000000
36          161.78
42           4.25
43     1842330000000
52          734.22
62           5.48
64          35.36
70     1180890000000
76          248.97
88     4457050000000
91          18.68
108    9174040000000
109    3196620000000
111         415.32
112         433.17
114         362.23
115    2548190000000
122         101.74
144         06.24
159         279.3
160          8.91
165         982.22
170    1032050000000
177    1015800000000
183          8.87
184         417.88
185         963.83
187    1257440000000
188         358.78
191         578.39
192    3993550000000
215         730.91
217    1923330000000
219         84.97
223         539.96
224         608.16
235         125.78
236    2352640000000
240          6.84
243    3101640000000
244     205635900000
246         235.54
Name: 2019 Real GDP, dtype: string

In [16]:
# slice to make 2019 real GDP column
df_a["2018 Real GDP"] = df_a["Real GDP"].str[52:]

#remove $ from new column
df_a["2018 Real GDP"] = df_a["2018 Real GDP"].str.replace("$", "")

# #remove billion
df_a["2018 Real GDP"] = df_a["2018 Real GDP"].str.replace("billion (2018 est.)", "")

# # #remove comma
df_a["2018 Real GDP"] = df_a["2018 Real GDP"].str.replace(",", "")

#remove comma
df_a["2018 Real GDP"] = df_a["2018 Real GDP"].str.replace(",", "")

#remove 19.\)
df_a["2018 Real GDP"] = df_a["2018 Real GDP"].str.replace("19 est.\)", "")

#remove .\)
df_a["2018 Real GDP"] = df_a["2018 Real GDP"].str.replace(".\)", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """
/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: The default value of regex will change from True to False in a future version.

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:17: FutureWarning: The default value of regex will change from True to False in a future version.
/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:20: FutureWarning: The default value of regex will change from True to False in a future version.

In [17]:
df_a["2018 Real GDP"]

10        1012670000000 (2018 est
15      )488.86 billion (2018 est
16       141.24 billion (2018 est
20       716.65 billion (2018 est
23       584.05 billion (2018 est
25         36.3 billion (2018 est
32        3072550000000 (2018 est
36       156.02 billion (2018 est
42        90.87 billion (2018 est
43        1808660000000 (2018 est
52       710.89 billion (2018 est
62        34.42 billion (2018 est
64      )326.07 billion (2018 est
70        1118720000000 (2018 est
76       229.76 billion (2018 est
88        4432430000000 (2018 est
91      )312.87 billion (2018 est
108       8817670000000 (2018 est
109       3043880000000 (2018 est
111      397.64 billion (2018 est
112      410.33 billion (2018 est
114      350.15 billion (2018 est
115       2540890000000 (2018 est
122       99.79 billion (2018 est
144     )868.85 billion (2018 est
159     )272.53 billion (2018 est
160       38.04 billion (2018 est
165      966.02 billion (2018 est
170       1009750000000 (2018 est
177       1005850000000 (2018 est
183       89.23 billion (2018 est
184      408.87 billion (2018 est
185      908.26 billion (2018 est
187       1202820000000 (2018 est
188      350.07 billion (2018 est
191      555.47 billion (2018 est
192       3913980000000 (2018 est
215       729.8 billion (2018 est
217       1886540000000 (2018 est
219     )278.68 billion (2018 est
223      532.67 billion (2018 est
224      601.65 billion (2018 est
235      124.48 billion (2018 est
236       2331270000000 (2018 est
240       90.67 billion (2018 est
243       3059690000000 (2018 est
244    2020128580000000 (2018 est
246      222.63 billion (2018 est
Name: 2018 Real GDP, dtype: string

In [18]:
#remove $ from new column
df_a["2018 Real GDP"] = df_a["2018 Real GDP"].str.replace("$", "")

#remove billion
df_a["2018 Real GDP"] = df_a["2019 Real GDP"].str.replace("billion (2018 est.)", "")

# #remove comma
df_a["2018 Real GDP"] = df_a["2018 Real GDP"].str.replace(",", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """

In [19]:
df_b = df_a.drop(["Real GDP"], axis = 1)

In [20]:
#check columns
#df_b.columns.tolist()

In [21]:
# split sting for  2019 GDP Growth Rate
df_b["GDP Growth Rate Est 1"] = df_b["GDP Growth Rate"].str[:15]

#remove the $
df_b["GDP Growth Rate Est 1"] = df_b["GDP Growth Rate Est 1"].str.replace("$", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """

In [22]:
df_b["GDP Growth Rate Est 1"]

10     -2.03% (2019 es
15     1.42% (2019 est
16     0.1% (2017 est.
20     7.4% (2017 est.
23     1.41% (2019 est
25     5.6% (2017 est.
32     1.13% (2019 est
36     3.39% (2019 est
42     3.5% (2017 est.
43     1.66% (2019 est
52     3.26% (2019 est
62     3.08% (2019 est
64     2.85% (2019 est
70     4.2% (2017 est.
76     10.9% (2017 est
88     0.59% (2019 est
91     1.87% (2019 est
108    4.86% (2019 est
109    5.03% (2019 est
111    -2.1% (2017 est
112    5.86% (2019 est
114    -2.6% (2020 est
115    0.34% (2019 est
122    2% (2019 est.)1
144    4.31% (2019 est
159    2.5% (2019 est.
160    3.11% (2018 est
165    1.63% (2019 est
170    0.8% (2017 est.
177    5.4% (2017 est.
183    4.8% (2017 est.
184    2.18% (2019 est
185    6.04% (2019 est
187    4.55% (2019 est
188    2.24% (2019 est
191    4.2% (2019 est.
192    1.34% (2019 est
215    0.06% (2019 est
217    1.95% (2019 est
219    2.29% (2019 est
223    1.29% (2019 est
224    1.11% (2019 est
235    2% (2017 est.)1
236    0.98% (2019 est
240    4.8% (2017 est.
243    1.26% (2019 est
244    2.16% (2019 est
246    5.3% (2017 est.
Name: GDP Growth Rate Est 1, dtype: string

In [23]:
df_b["GDP Growth Rate Est 2"] = df_b["GDP Growth Rate"].str[15:31]

# #remove ) - need remove without adding period
#df_b["GDP Growth Rate Est 2"] = df_b["GDP Growth Rate Est 2"].str.replace("\)", "")

# #remove .)
df_b["GDP Growth Rate Est 2"] = df_b["GDP Growth Rate Est 2"].str.replace(".\)", "")

# #remove t
df_b["GDP Growth Rate Est 2"] = df_b["GDP Growth Rate Est 2"].str.replace("t", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  import sys

In [24]:
df_b["GDP Growth Rate Est 2"]

10       -2.53% (2018
15      2.58% (2018 es
16     )-3.1% (2016 es
20     )7.2% (2016 es.
23      1.49% (2018 es
25       )4% (2016 es2
32       1.2% (2018 es
36       3.2% (2018 es
42     )4.6% (2016 es.
43      2.02% (2018 es
52      2.51% (2018 es
62      5.25% (2018 es
64      2.18% (2018 es
70     )4.3% (2016 es.
76         8% (2016 es
88       1.3% (2018 es
91      1.91% (2018 es
108     6.78% (2018 es
109     5.17% (2018 es
111     13.1% (2016 es
112     9.42% (2018 es
114     3.28% (2019 es
115     0.83% (2018 es
122      .94% (2018 es
144     4.77% (2018 es
159    )2.96% (2018 es
160      3.7% (2017 es
165     2.32% (2018 es
170    )-1.6% (2016 es
177    )4.6% (2016 es.
183    )4.3% (2016 es.
184     3.97% (2018 es
185     6.34% (2018 es
187     5.36% (2018 es
188     2.85% (2018 es
191    )4.54% (2018 es
192     2.54% (2018 es
215      0.7% (2018 es
217     2.43% (2018 es
219     3.32% (2018 es
223     2.06% (2018 es
224     3.04% (2018 es
235      .1% (2016 es1
236     3.04% (2018 es
240    )2.3% (2016 es.
243     1.25% (2018 es
244        3% (2018 es
246    )7.8% (2016 es.
Name: GDP Growth Rate Est 2, dtype: string

In [25]:
df_b["GDP Growth Rate Est 3"] = df_b["GDP Growth Rate"].str[32:]

# # #remove .) need to remove without adding period
#df_b["GDP Growth Rate Est 3"] = df_b["GDP Growth Rate Est 3"].str.replace("\)", "")

# # #remove .)
df_b["GDP Growth Rate Est 3"] = df_b["GDP Growth Rate Est 3"].str.replace(".\)", "")

# # #remove t
df_b["GDP Growth Rate Est 3"] = df_b["GDP Growth Rate Est 3"].str.replace("st", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  import sys

In [26]:
df_b["GDP Growth Rate Est 3"]

10      2.83% (2017 e
15       2.4% (2017 e
16      )0.6% (2015 e
20       6.8% (2015 e
23       1.9% (2017 e
25         1% (2015 e
32     )1.62% (2017 e
36      )3.5% (2017 e
42       5.7% (2015 e
43      3.17% (2017 e
52      1.36% (2017 e
62      5.16% (2017 e
64      2.83% (2017 e
70       4.4% (2015 e
76       0.4% (2015 e
88     )2.91% (2017 e
91      1.44% (2017 e
108     6.55% (2017 e
109     5.07% (2017 e
111      2.5% (2015 e
112     9.49% (2017 e
114     3.69% (2018 e
115     1.73% (2017 e
122      .12% (2017 e
144     5.81% (2017 e
159    )3.98% (2017 e
160    )4.07% (2017 e
165     3.02% (2017 e
170     )2.7% (2015 e
177      4.1% (2015 e
183      3.1% (2015 e
184     2.48% (2017 e
185     6.94% (2017 e
187     4.83% (2017 e
188     3.51% (2017 e
191    )7.11% (2017 e
192     1.83% (2017 e
215     )1.4% (2017 e
217     2.97% (2017 e
219     3.58% (2017 e
223     2.82% (2017 e
224     1.65% (2017 e
235        2% (2015 e
236     7.54% (2017 e
240      5.7% (2015 e
243     1.74% (2017 e
244      .33% (2017 e
246      7.9% (2015 e
Name: GDP Growth Rate Est 3, dtype: string

In [27]:
#check columns
#df_b.columns.tolist()

In [28]:
#drop GDP Growth Rate'
df_c = df_b.drop(["GDP Growth Rate"], axis = 1)

In [29]:
#check columns
#df_c.columns.tolist()

In [30]:
# slice for GDP per Capita est 1
df_c["GDP per Capita Est 1"] = df_c["GDP per Capita"].str[:19]

#remove the $
df_c["GDP per Capita Est 1"] = df_c["GDP per Capita Est 1"].str.replace("$", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """

In [31]:
#check results
#df_c["GDP per Capita Est 1"]

In [32]:
# slice for GDP per Capita est 2
df_c["GDP per Capita Est 2"] = df_c["GDP per Capita"].str[19:38]

#remove the $
df_c["GDP per Capita Est 2"] = df_c["GDP per Capita Est 2"].str.replace("$", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """

In [33]:
#check results
#df_c["GDP per Capita Est 2"]

In [34]:
# slice for GDP per Capita est 3
df_c["GDP per Capita Est 3"] = df_c["GDP per Capita"].str[35:]

#remove the t.)
df_c["GDP per Capita Est 3"] = df_c["GDP per Capita Est 3"].str.replace("t.\)", "")

#remove the t.)
df_c["GDP per Capita Est 3"] = df_c["GDP per Capita Est 3"].str.replace(".\)", "")

#remove the $
df_c["GDP per Capita Est 3"] = df_c["GDP per Capita Est 3"].str.replace("$", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """
/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: The default value of regex will change from True to False in a future version.

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:11: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  # This is added back by InteractiveShellApp.init_path()

In [35]:
#check results
#df_c["GDP per Capita Est 3"]

In [36]:
#check columns
#df_c.columns.tolist()

In [37]:
#create slice for Econ Current Acct Bal
df_c["Econ: Current Acct Bal Est 1"] = df_c["Econ Current Acct Bal"].str[:26]

In [38]:
#check columns
#df_c["Econ: Current Acct Bal Est 1"]

In [39]:
#create slice for Econ Current Acct Bal Est 2
df_c["Econ: Current Acct Bal Est 2"] = df_c["Econ Current Acct Bal"].str[27:]

In [40]:
#check columns
#df_c["Econ: Current Acct Bal Est 2"]

In [41]:
#check results df_c
#df_c.head()
df_c.columns.tolist()

['Country',
 'Geographic coordinates',
 'Map references',
 'Geography: Area - total',
 'GDP per Capita',
 'Econ Current Acct Bal',
 'Exports',
 'Exports - Partners',
 'Foreign Exchange & Gold',
 'Tota; Population Electrication',
 "Moody's Rating",
 'Standard & Poors Rating',
 'Fitch Rating',
 'Unemployment Rate',
 'Population below poverty line',
 'Household income or consumption by % -highest 10%',
 'Population',
 'Nationality - noun',
 'Nationality - adjective',
 'Languages',
 'Religions',
 'Age structure - 0-14 years',
 'Age structure - 15-24 years',
 'Age structure - 25-54 years',
 'Age structure - 55-64 years',
 'Total Median age',
 'Male Median age',
 'Female Median age',
 'Population growth rate',
 'Birth rate',
 'Death rate',
 'Net migration rate',
 'Urban Population',
 'Sex ratio at Birth',
 '65 & Older Sex Ratio',
 'Total Pop Sex Ratio',
 'Total Infant Mortality Rate',
 'Total Pop Life expectancy at birth',
 'Male Life expectancy at birth',
 'Female Life expectancy at birth',
 'Total fertility rate',
 'Adult Obesity Prev Rate',
 'Total Tobacco use',
 'Total Internet Users',
 'Internet users - % of Pop',
 'Military expenditures',
 'Military service age and obligation',
 'Terrorism: Terrorist group(s)',
 'Military and Security: Military - note',
 'LATITUDE',
 'LONGITUDE',
 '2020 Real GDP',
 '2019 Real GDP',
 '2018 Real GDP',
 'GDP Growth Rate Est 1',
 'GDP Growth Rate Est 2',
 'GDP Growth Rate Est 3',
 'GDP per Capita Est 1',
 'GDP per Capita Est 2',
 'GDP per Capita Est 3',
 'Econ: Current Acct Bal Est 1',
 'Econ: Current Acct Bal Est 2']

In [42]:
#create slice for export
df_c["Exports Est 1"] = df_c["Exports"].str[:26]
#remove the $
df_c["Exports Est 1"] = df_c["Exports Est 1"].str.replace("$", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  after removing the cwd from sys.path.

In [43]:
#check results
#df_c["Exports Est 1"]

In [44]:
#create slice for second export category
df_c["Exports Est 2"] = df_c["Exports"].str[65:91]

#remove the s
df_c["Exports Est 2"] = df_c["Exports Est 2"].str.replace("s", "")

#remove the $
df_c["Exports Est 2"] = df_c["Exports Est 2"].str.replace("$", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

In [45]:
#df_c["Exports Est 2"]

In [46]:
#make slice for top export partner
df_c["Top Export - Country & %"] = df_c["Exports - Partners"].str[:15]

In [47]:
#check results
#df_c["Top Export - Country & %"]
df_c.columns.tolist()

['Country',
 'Geographic coordinates',
 'Map references',
 'Geography: Area - total',
 'GDP per Capita',
 'Econ Current Acct Bal',
 'Exports',
 'Exports - Partners',
 'Foreign Exchange & Gold',
 'Tota; Population Electrication',
 "Moody's Rating",
 'Standard & Poors Rating',
 'Fitch Rating',
 'Unemployment Rate',
 'Population below poverty line',
 'Household income or consumption by % -highest 10%',
 'Population',
 'Nationality - noun',
 'Nationality - adjective',
 'Languages',
 'Religions',
 'Age structure - 0-14 years',
 'Age structure - 15-24 years',
 'Age structure - 25-54 years',
 'Age structure - 55-64 years',
 'Total Median age',
 'Male Median age',
 'Female Median age',
 'Population growth rate',
 'Birth rate',
 'Death rate',
 'Net migration rate',
 'Urban Population',
 'Sex ratio at Birth',
 '65 & Older Sex Ratio',
 'Total Pop Sex Ratio',
 'Total Infant Mortality Rate',
 'Total Pop Life expectancy at birth',
 'Male Life expectancy at birth',
 'Female Life expectancy at birth',
 'Total fertility rate',
 'Adult Obesity Prev Rate',
 'Total Tobacco use',
 'Total Internet Users',
 'Internet users - % of Pop',
 'Military expenditures',
 'Military service age and obligation',
 'Terrorism: Terrorist group(s)',
 'Military and Security: Military - note',
 'LATITUDE',
 'LONGITUDE',
 '2020 Real GDP',
 '2019 Real GDP',
 '2018 Real GDP',
 'GDP Growth Rate Est 1',
 'GDP Growth Rate Est 2',
 'GDP Growth Rate Est 3',
 'GDP per Capita Est 1',
 'GDP per Capita Est 2',
 'GDP per Capita Est 3',
 'Econ: Current Acct Bal Est 1',
 'Econ: Current Acct Bal Est 2',
 'Exports Est 1',
 'Exports Est 2',
 'Top Export - Country & %']

In [48]:
#create foreign exchange and gold column based on most recent figure
df_c["Foreign Exchange & Gold - latest est"] = df_c['Foreign Exchange & Gold'].str[:39]

#remove the $
df_c["Foreign Exchange & Gold - latest est"] = df_c["Foreign Exchange & Gold - latest est"].str.replace("$", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """

In [49]:
#check results
#df_c["Foreign Exchange & Gold - latest est"]

In [50]:
#### create slice for electic access results are on 2020/2019
df_c["Total Population Electrification (2020 - 2019)"] = df_c["Tota; Population Electrication"].str[:4]

In [51]:
#check result
#df_c["Total Population Electrification (2020 - 2019)"]

In [52]:
#took the latest metric (results are between 2017 to 2020)
df_c["Unemployment Rate (recent)"] = df_c["Unemployment Rate"].str[:4]

#remove the "("
df_c["Unemployment Rate (recent)"] = df_c["Unemployment Rate (recent)"].str.replace("\(", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """

In [53]:
#check the results:
#df_c["Unemployment Rate (recent)"]

In [54]:
# create slice for population below poverty line.  Only one set of results per country 
df_c["Percent Population below poverty line"] = df_c["Population below poverty line"].str[:5]

In [55]:
#remove the (  from some results
df_c["Percent Population below poverty line"] = df_c["Percent Population below poverty line"].str.replace("\(", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

In [56]:
#check results
#df_c["Percent Population below poverty line"]

In [57]:
# create slice for population below poverty line.  Only one set of results per country 
df_c["Population below poverty line - Year Recorded"] = df_c["Population below poverty line"].str[5:]

In [58]:
#remove the (  from some results
df_c["Population below poverty line - Year Recorded"] = df_c["Population below poverty line - Year Recorded"].str.replace("\(", "") 

#remove the est.
df_c["Population below poverty line - Year Recorded"] = df_c["Population below poverty line - Year Recorded"].str.replace("est.\)", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """

In [59]:
#check results
#df_c["Population below poverty line - Year Recorded"]

In [60]:
# create slice for population below poverty line.  Only one set of results per country 
df_c["Household income or consumption by % (-highest 10%)"] = df_c["Household income or consumption by % -highest 10%"].str[:4]

In [61]:
#check results
#df_c["Household income or consumption by % (-highest 10%)"]

In [62]:
# create slice for population below poverty line.  Only one set of results per country 
df_c["Household income or consumption by % (year recorded)"] = df_c["Household income or consumption by % -highest 10%"].str[5:]

In [63]:
#remove the (  from some results
df_c["Household income or consumption by % (year recorded)"] = df_c["Household income or consumption by % (year recorded)"].str.replace("\(", "") 

#remove the est.
df_c["Household income or consumption by % (year recorded)"] = df_c["Household income or consumption by % (year recorded)"].str.replace("est.\)", "") 

#remove )
#remove the (  from some results
df_c["Household income or consumption by % (year recorded)"] = df_c["Household income or consumption by % (year recorded)"].str.replace("\)", "") 

#remove FY
df_c["Household income or consumption by % (year recorded)"] = df_c["Household income or consumption by % (year recorded)"].str.replace("FY", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """
/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:9: FutureWarning: The default value of regex will change from True to False in a future version.
  if __name__ == '__main__':

In [64]:
#check results
#df_c["Household income or consumption by % (year recorded)"]

In [65]:
df_c["Population (as of 2022)"] = df_c["Population"].str[:11]

In [66]:
#remove the (  from some results
df_c["Population (as of 2022)"] = df_c["Population (as of 2022)"].str.replace("\(", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

In [67]:
#check results
#df_c["Population (as of 2022)"]

In [68]:
df_c.columns.tolist()

['Country',
 'Geographic coordinates',
 'Map references',
 'Geography: Area - total',
 'GDP per Capita',
 'Econ Current Acct Bal',
 'Exports',
 'Exports - Partners',
 'Foreign Exchange & Gold',
 'Tota; Population Electrication',
 "Moody's Rating",
 'Standard & Poors Rating',
 'Fitch Rating',
 'Unemployment Rate',
 'Population below poverty line',
 'Household income or consumption by % -highest 10%',
 'Population',
 'Nationality - noun',
 'Nationality - adjective',
 'Languages',
 'Religions',
 'Age structure - 0-14 years',
 'Age structure - 15-24 years',
 'Age structure - 25-54 years',
 'Age structure - 55-64 years',
 'Total Median age',
 'Male Median age',
 'Female Median age',
 'Population growth rate',
 'Birth rate',
 'Death rate',
 'Net migration rate',
 'Urban Population',
 'Sex ratio at Birth',
 '65 & Older Sex Ratio',
 'Total Pop Sex Ratio',
 'Total Infant Mortality Rate',
 'Total Pop Life expectancy at birth',
 'Male Life expectancy at birth',
 'Female Life expectancy at birth',
 'Total fertility rate',
 'Adult Obesity Prev Rate',
 'Total Tobacco use',
 'Total Internet Users',
 'Internet users - % of Pop',
 'Military expenditures',
 'Military service age and obligation',
 'Terrorism: Terrorist group(s)',
 'Military and Security: Military - note',
 'LATITUDE',
 'LONGITUDE',
 '2020 Real GDP',
 '2019 Real GDP',
 '2018 Real GDP',
 'GDP Growth Rate Est 1',
 'GDP Growth Rate Est 2',
 'GDP Growth Rate Est 3',
 'GDP per Capita Est 1',
 'GDP per Capita Est 2',
 'GDP per Capita Est 3',
 'Econ: Current Acct Bal Est 1',
 'Econ: Current Acct Bal Est 2',
 'Exports Est 1',
 'Exports Est 2',
 'Top Export - Country & %',
 'Foreign Exchange & Gold - latest est',
 'Total Population Electrification (2020 - 2019)',
 'Unemployment Rate (recent)',
 'Percent Population below poverty line',
 'Population below poverty line - Year Recorded',
 'Household income or consumption by % (-highest 10%)',
 'Household income or consumption by % (year recorded)',
 'Population (as of 2022)']

In [69]:
#slice for percent 14 and under
df_c["Percent of People 14 yrs and under"] = df_c["Age structure - 0-14 years"].str[:5]

In [70]:
#check results
#df_c["Percent of People 14 yrs and under"]

In [71]:
#slice for males 14 and under
df_c["males 14 yrs and under"] = df_c["Age structure - 0-14 years"].str[12:22]

In [72]:
#remove the /f
df_c["males 14 yrs and under"] = df_c["males 14 yrs and under"].str.replace("/f", "")

In [73]:
#check results
#df_c["males 14 yrs and under"]

In [74]:
#slice for females 14 and under
df_c["females 14 yrs and under"] = df_c["Age structure - 0-14 years"].str[28:]

In [75]:
#remove remove letters
df_c["females 14 yrs and under"] = df_c["females 14 yrs and under"].str.replace("[l, e, a]", "") 

#remove )
df_c["females 14 yrs and under"] = df_c["females 14 yrs and under"].str.replace("\)", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """

In [76]:
#check results
#df_c["females 14 yrs and under"]

In [77]:
#slice for percent 15- 24 and under
df_c["Percent of People 15-24 yrs and under"] = df_c["Age structure - 15-24 years"].str[:5]

In [78]:
#check results
#df_c["Percent of People 15-24 yrs and under"]

In [79]:
#slice for males 15-24 and under
df_c["males between 15-24 years"] = df_c["Age structure - 15-24 years"].str[12:22]

In [80]:
#remove /
df_c["males between 15-24 years"] = df_c["males between 15-24 years"].str.replace("/", "") 
#remove letters
df_c["males between 15-24 years"] = df_c["males between 15-24 years"].str.replace("[f, e, m]", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  after removing the cwd from sys.path.

In [81]:
#check results
#df_c["males between 15-24 years"]

In [82]:
#slice for fmales 15-24 and under
df_c["females between 15-24 years"] = df_c["Age structure - 15-24 years"].str[28:]

In [83]:
#remove remove letters
df_c["females between 15-24 years"] = df_c["females between 15-24 years"].str.replace("[l, e, a]", "") 

#remove )
df_c["females between 15-24 years"] = df_c["females between 15-24 years"].str.replace("\)", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """

In [84]:
#df_c["females between 15-24 years"]

In [85]:
#slice for percent 25 - 54 and under
df_c["Percent of People 25-54 yrs"] = df_c["Age structure - 25-54 years"].str[:5]

In [86]:
#check results
#df_c["Percent of People 25-54 yrs"]

In [87]:
#slice for males 25-54 
df_c["males 25-54 yrs"] = df_c["Age structure - 25-54 years"].str[11:23]

In [88]:
#remove /
df_c["males 25-54 yrs"] = df_c["males 25-54 yrs"].str.replace("/", "") 
#remove letters
df_c["males 25-54 yrs"] = df_c["males 25-54 yrs"].str.replace("[f, e, m]", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  after removing the cwd from sys.path.

In [89]:
#check results
#df_c["males 25-54 yrs"]

In [90]:
#slice for females 25-54 and under
df_c["females 25-54 yrs"] = df_c["Age structure - 25-54 years"].str[28:]

In [91]:
#remove remove letters
df_c["females 25-54 yrs"] = df_c["females 25-54 yrs"].str.replace("[l, e, a]", "") 

#remove )
df_c["females 25-54 yrs"] = df_c["females 25-54 yrs"].str.replace("\)", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """

In [92]:
#check results
#df_c["females 25-54 yrs"]

In [93]:
#slice for percent 55-64
df_c["Percent of People 55-64"] = df_c["Age structure - 55-64 years"].str[:5]

In [94]:
#check results
#df_c["Percent of People 55-64"]

In [95]:
#slice for males 55-64
df_c["males 55-64 yrs"] = df_c["Age structure - 55-64 years"].str[11:23]

In [96]:
#remove /
df_c["males 55-64 yrs"] = df_c["males 55-64 yrs"].str.replace("/", "") 
#remove letters
df_c["males 55-64 yrs"] = df_c["males 55-64 yrs"].str.replace("[f, e, m]", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  after removing the cwd from sys.path.

In [97]:
#check results
#df_c["males 55-64 yrs"]

In [98]:
#slice for females 55-64
df_c["females 55-64 yrs"] = df_c["Age structure - 25-54 years"].str[28:]

In [99]:
#remove remove letters
df_c["females 55-64 yrs"] = df_c["females 55-64 yrs"].str.replace("[l, e, a]", "") 

#remove )
df_c["females 55-64 yrs"] = df_c["females 55-64 yrs"].str.replace("\)", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """

In [100]:
#check results
#df_c["females 55-64 yrs"]

In [101]:
#reformat total median age column
df_c["Median Age (in years)"] = df_c["Total Median age"].str[:4]

In [102]:
#check results
#df_c["Median Age (in years)"]

In [103]:
# male median age column
df_c["Male Median Age (in years)"] = df_c["Male Median age"].str[:4]

In [104]:
#check results
#df_c["Male Median Age (in years)"]

In [105]:
#female median age column
df_c["Female Median Age (in years)"] = df_c["Female Median age"].str[:4]

In [106]:
#check results
#df_c["Female Median Age (in years)"]

In [107]:
#pop growth rate column
df_c["Population growth rate (2022 est)"] = df_c["Population growth rate"].str[:5]

In [108]:
#check results
#df_c["Population growth rate (based on 2022 estimates)"]

In [109]:
#birth rate column
df_c["Birth rate (births/1,000 population, 2022 est)"] = df_c["Birth rate"].str[:5]

In [110]:
#check results
#df_c["Birth rate (births/1,000 population, 2022 estimates)"]

In [111]:
#death rate column
df_c["Death rate (births/1,000 population, 2022 estimates)"] = df_c["Death rate"].str[:5]

In [112]:
#check results
#df_c["Death rate (births/1,000 population, 2022 estimates)"]

In [113]:
#net migration rate
df_c["Net migration rate (migrant(s)/1,000 population, 2022 est.)"] = df_c["Net migration rate"].str[:5]

In [114]:
#remove letters
df_c["Net migration rate (migrant(s)/1,000 population, 2022 est.)"] = df_c["Net migration rate (migrant(s)/1,000 population, 2022 est.)"].str.replace("[m,i,g]", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

In [115]:
#check results
#df_c["Net migration rate (migrant(s)/1,000 population, 2022 est.)"]

In [116]:
#urban population column - percentage
df_c["Urban Population (- % of total pop as of 2022)"] = df_c["Urban Population"].str[:5]

In [117]:
#check results
#df_c["Urban Population (- % of total pop as of 2022)"]

In [118]:
#sex rate at birth 
df_c["Sex ratio at Birth (male(s)/female)"] = df_c["Sex ratio at Birth"].str[:5]

In [119]:
#check results
#df_c["Sex ratio at Birth (male(s)/female)"]

In [120]:
#sex ratio 65 and older
df_c["65 & Older Sex Ratio (male(s)/female)"] = df_c["65 & Older Sex Ratio"].str[:5]

In [121]:
#check results
#df_c["65 & Older Sex Ratio (male(s)/female)"]

In [122]:
#sex ratio total population
df_c["Total Pop Sex Ratio (male(s)/female, as of 2022"] = df_c["Total Pop Sex Ratio"].str[:4]

In [123]:
#remove letters
df_c["Total Pop Sex Ratio (male(s)/female, as of 2022"] = df_c["Total Pop Sex Ratio (male(s)/female, as of 2022"].str.replace("[m,a]", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

In [124]:
#check results
#df_c["Total Pop Sex Ratio (male(s)/female, as of 2022"]

In [125]:
#infant mortality rate column
df_c["Total Infant Mortality Rate (deaths/1,000 live births)"] = df_c["Total Infant Mortality Rate"].str[:5]

In [126]:
#check results
#df_c["Total Infant Mortality Rate (deaths/1,000 live births)"]

In [127]:
# life expectancy at birth
df_c["Total Pop Life expectancy at birth (in years)"] = df_c["Total Pop Life expectancy at birth"].str[:5]

In [128]:
#check results
#df_c["Total Pop Life expectancy at birth (in years)"]

In [129]:
#male life expectancy at birth
df_c["Male Life expectancy at birth (in years)"] = df_c["Male Life expectancy at birth"].str[:5]

In [130]:
#check results
#df_c["Male Life expectancy at birth (in years)"]

In [131]:
df_c["Female Life expectancy at birth (in years, 2022 est.)"] = df_c["Female Life expectancy at birth"].str[:5]

In [132]:
#check results
#df_c["Female Life expectancy at birth (in years, 2022 est.)"]

In [133]:
#Total fertility rate column
df_c["Total fertility rate (children born/woman (2022 est.)"] = df_c["Total fertility rate"].str[:5]

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`

In [134]:
#remove letters
df_c["Total fertility rate (children born/woman (2022 est.)"] = df_c["Total fertility rate (children born/woman (2022 est.)"].str.replace("[c]", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

In [135]:
#check results
#df_c["Total fertility rate (children born/woman (2022 est.)"]

In [136]:
#obesity rate column
df_c["Adult Obesity Prev Rate in percentages (2016 est.)"] = df_c["Adult Obesity Prev Rate"].str[:5]

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`

In [137]:
#remove letters
df_c["Adult Obesity Prev Rate in percentages (2016 est.)"] = df_c["Adult Obesity Prev Rate in percentages (2016 est.)"].str.replace("\(", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

In [138]:
#check column
#df_c["Adult Obesity Prev Rate in percentages (2016 est.)"]

In [139]:
#tobacco use
df_c["Total Tobacco use in percentages (2020 est.)"] = df_c["Total Tobacco use"].str[:5]

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`

In [140]:
#remove )
df_c["Total Tobacco use in percentages (2020 est.)"] = df_c["Total Tobacco use in percentages (2020 est.)"].str.replace("\(", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

In [141]:
#check result
#df_c["Total Tobacco use in percentages (2020 est.)"]

In [142]:
#internet users column
df_c["Total Internet Users (2020 est.)"] = df_c["Total Internet Users"].str[:10]

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`

In [143]:
#remove letters
df_c["Total Internet Users (2020 est.)"] = df_c["Total Internet Users (2020 est.)"].str.replace("[m,i,l]", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

In [144]:
#check result
#df_c["Total Internet Users (2020 est.)"]

In [145]:
#internet users percent column
df_c["Internet users - % of Pop (2020 est.)"] = df_c["Internet users - % of Pop"].str[:4]

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`

In [146]:
#check result
#df_c["Internet users - % of Pop (2020 est.)"]

In [147]:
#2021 military expenditures
df_c["2021 Military expenditures (as percent of GDP)"] = df_c["Military expenditures"].str[:3]

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`

In [148]:
#check results
#df_c["2021 Military expenditures (as percent of GDP)"]

In [149]:
#2020 military expenditures
df_c["2020 Military expenditures (as percent of GDP)"] = df_c["Military expenditures"].str[20:29]

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`

In [150]:
#remove letters
df_c["2020 Military expenditures (as percent of GDP)"] = df_c["2020 Military expenditures (as percent of GDP)"].str.replace("[t, o, f, g, d, p, G, D, P]", "") 

#remove .)
#remove letters
df_c["2020 Military expenditures (as percent of GDP)"] = df_c["2020 Military expenditures (as percent of GDP)"].str.replace(".\)", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:6: FutureWarning: The default value of regex will change from True to False in a future version.

In [151]:
#check results
#df_c["2020 Military expenditures (as percent of GDP)"]

In [152]:
#2019 military expenditures
df_c["2019 Military expenditures (as percent of GDP)"] = df_c["Military expenditures"].str[38:51]

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`

In [153]:
#remove letters
df_c["2019 Military expenditures (as percent of GDP)"] = df_c["2019 Military expenditures (as percent of GDP)"].str.replace("[t, o, f, g, d, p, G, D, P, e, s]", "") 

#remove .)
#remove letters
df_c["2019 Military expenditures (as percent of GDP)"] = df_c["2019 Military expenditures (as percent of GDP)"].str.replace(".\)", "")

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

/Users/laurenerminina/opt/anaconda3/envs/PythonData/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:6: FutureWarning: The default value of regex will change from True to False in a future version.

In [154]:
#check results - some cleaning needed
df_c["2019 Military expenditures (as percent of GDP)"]

10        20.7%
15       200.7%
16       203.8%
20       201.4%
23        )0.9%
25       200.5%
32        21.4%
36        23.1%
42         1.4%
43        21.3%
52         3.1%
62         1.6%
64        21.3%
70        21.3%
76       200.6%
88        21.4%
91        22.3%
108      202.4%
109       20.8%
111      203.8%
112       3%(20
114        5.2%
115       21.2%
122        5.6%
144       )1%(2
159      203.4%
160      201.2%
165       21.3%
170      200.5%
177          4%
183          1%
184      201.2%
185       21.1%
187         22%
188       21.4%
191       .8%(2
192        3.8%
215         21%
217       .9%(2
219          2%
223       21.1%
224       20.7%
235        3.8%
236       21.9%
240      201.7%
243       22.1%
244       23.4%
246    $3billi2
Name: 2019 Military expenditures (as percent of GDP), dtype: string

In [155]:
#create new df dropped "cleaned" columns

df_d = pd.DataFrame(df_c)

In [156]:
df_e = df_c.drop(['GDP per Capita',
     'Econ Current Acct Bal',
     'Exports',
     'Exports - Partners',
     'Foreign Exchange & Gold',
     'Tota; Population Electrication',
     "Moody's Rating",
     'Standard & Poors Rating',
     'Fitch Rating',
     'Unemployment Rate',
     'Population below poverty line',
     'Household income or consumption by % -highest 10%',
     'Population',
     'Nationality - noun',
     'Nationality - adjective',
     'Languages',
     'Religions',
     'Age structure - 0-14 years',
     'Age structure - 15-24 years',
     'Age structure - 25-54 years',
     'Age structure - 55-64 years',
     'Total Median age',
     'Male Median age',
     'Female Median age',
     'Population growth rate',
     'Birth rate',
     'Death rate',
     'Net migration rate',
     'Urban Population',
     'Sex ratio at Birth',
     '65 & Older Sex Ratio',
     'Total Pop Sex Ratio',
     'Total Infant Mortality Rate',
     'Total Pop Life expectancy at birth',
     'Male Life expectancy at birth',
     'Female Life expectancy at birth',
     'Total fertility rate',
     'Adult Obesity Prev Rate',
     'Total Tobacco use',
     'Total Internet Users',
     'Internet users - % of Pop',
     'Military expenditures'], axis=1)

In [157]:
df_e.head()

,Country,Geographic coordinates,Map references,Geography: Area - total,Military service age and obligation,Terrorism: Terrorist group(s),Military and Security: Military - note,LATITUDE,LONGITUDE,2020 Real GDP,...,Male Life expectancy at birth (in years),"Female Life expectancy at birth (in years, 2022 est.)",Total fertility rate (children born/woman (2022 est.),Adult Obesity Prev Rate in percentages (2016 est.),Total Tobacco use in percentages (2020 est.),Total Internet Users (2020 est.),Internet users - % of Pop (2020 est.),2021 Military expenditures (as percent of GDP),2020 Military expenditures (as percent of GDP),2019 Military expenditures (as percent of GDP)
10,Argentina,"34 00 S, 64 00 W",South America,"2,780,400 sq km",18-24 years of age for voluntary military serv...,Hizballah,Argentina has Major Non-NATO Ally (MNNA) statu...,34 00 S,64 00 W,893.31,...,75.23,81.59,2.18,28.3%,24.5%,39024016,86%,0.8,0.8%,20.7%
15,Austria,"47 20 N, 13 20 E",Europe,"83,871 sq km","registration requirement at age 17, the legal ...",Islamic State of Iraq and ash-Sham (ISIS),"Austria is constitutionally non-aligned, but i...",47 20 N,13 20 E,463.12,...,79.64,85.04,1.51,20.1%,26.4%,7846840,88%,0.9,0.7%,200.7%
16,Azerbaijan,"40 30 N, 47 30 E",Asia,"86,600 sq km",men age 18-35 years for compulsory military se...,Islamic State of Iraq and ash-Sham (ISIS); Isl...,"since November 2020, Russia has deployed about...",40 30 N,47 30 E,138.51,...,71.08,77.41,1.86,19.9%,24%,8579153,85%,5.2,5.4%,203.8%
20,Bangladesh,"24 00 N, 90 00 E",Asia,"148,460 sq km",16-21 years of age for voluntary military serv...,Harakat ul-Jihad-i-Islami/Bangladesh; Islamic ...,the military’s chief areas of focus are border...,24 00 N,90 00 E,793.49,...,72.52,76.96,2.09,3.6%,34.7%,41172346,25%,1.2,1.3%,201.4%
23,Belgium,"50 50 N, 4 00 E",Europe,"30,528 sq km",18 years of age for male and female voluntary ...,Islamic Revolutionary Guard Corps/Qods Force; ...,Belgium is a member of NATO and was one of the...,50 50 N,4 00 E,557.11,...,79.25,84.59,1.77,22.1%,23.4%,10620701,92%,1.1,1%,)0.9%

In [158]:
df_e.columns.tolist()

['Country',
 'Geographic coordinates',
 'Map references',
 'Geography: Area - total',
 'Military service age and obligation',
 'Terrorism: Terrorist group(s)',
 'Military and Security: Military - note',
 'LATITUDE',
 'LONGITUDE',
 '2020 Real GDP',
 '2019 Real GDP',
 '2018 Real GDP',
 'GDP Growth Rate Est 1',
 'GDP Growth Rate Est 2',
 'GDP Growth Rate Est 3',
 'GDP per Capita Est 1',
 'GDP per Capita Est 2',
 'GDP per Capita Est 3',
 'Econ: Current Acct Bal Est 1',
 'Econ: Current Acct Bal Est 2',
 'Exports Est 1',
 'Exports Est 2',
 'Top Export - Country & %',
 'Foreign Exchange & Gold - latest est',
 'Total Population Electrification (2020 - 2019)',
 'Unemployment Rate (recent)',
 'Percent Population below poverty line',
 'Population below poverty line - Year Recorded',
 'Household income or consumption by % (-highest 10%)',
 'Household income or consumption by % (year recorded)',
 'Population (as of 2022)',
 'Percent of People 14 yrs and under',
 'males 14 yrs and under',
 'females 14 yrs and under',
 'Percent of People 15-24 yrs and under',
 'males between 15-24 years',
 'females between 15-24 years',
 'Percent of People 25-54 yrs',
 'males 25-54 yrs',
 'females 25-54 yrs',
 'Percent of People 55-64',
 'males 55-64 yrs',
 'females 55-64 yrs',
 'Median Age (in years)',
 'Male Median Age (in years)',
 'Female Median Age (in years)',
 'Population growth rate (2022 est)',
 'Birth rate (births/1,000 population, 2022 est)',
 'Death rate (births/1,000 population, 2022 estimates)',
 'Net migration rate (migrant(s)/1,000 population, 2022 est.)',
 'Urban Population (- % of total pop as of 2022)',
 'Sex ratio at Birth (male(s)/female)',
 '65 & Older Sex Ratio (male(s)/female)',
 'Total Pop Sex Ratio (male(s)/female, as of 2022',
 'Total Infant Mortality Rate (deaths/1,000 live births)',
 'Total Pop Life expectancy at birth (in years)',
 'Male Life expectancy at birth (in years)',
 'Female Life expectancy at birth (in years, 2022 est.)',
 'Total fertility rate (children born/woman (2022 est.)',
 'Adult Obesity Prev Rate in percentages (2016 est.)',
 'Total Tobacco use in percentages (2020 est.)',
 'Total Internet Users (2020 est.)',
 'Internet users - % of Pop (2020 est.)',
 '2021 Military expenditures (as percent of GDP)',
 '2020 Military expenditures (as percent of GDP)',
 '2019 Military expenditures (as percent of GDP)']

In [159]:
#export to csv
df_e.to_csv("intermed_clean_cia.csv")